### ISSUE TITLE
[BUG] orgTag should also define the preview-list

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#205]
## Bug 
Unaproved changes should never be visible on a map with activated orgTag-mode!

This map has the orgTag mode activated (defined by &orgTag=hessenwillsmessen in the URL) https://www.kartevonmorgen.org/m/hessenwillsmessen?c=50.6142%2C8.3633&z=9.46&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=&search=test

The Test-Entry and the word "Test" in the description of the backery got never approved in the clearance-center. But still it is visibel:
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/1394fec3-83b2-4c76-af46-f72dfa38723d)

When you click on the entry, the detailed view is correct as it shows no "Test" in the description: https://www.kartevonmorgen.org/m/hessenwillsmessen/e/3fada349903f4d129f6cd918f67094c9?c=50.6142%2C8.3633&z=9.46&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=&search=test
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/874db919-bcac-4b0b-8986-54ba8f774130)

Opening the test entry does not show anything, which is basically correct, because it is not allowed to show someting. But the entry should not displayed on the map as a dot and not in the list, so no user should be able to click on it.
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/2b02f203-a6de-4eed-8b69-fecdff513712)

## Expected behavior
On the old Frontend you see the correct behavior: The test entry is not visible at all and the "Test" in the backery descritpion does not appear: 
https://v0.kartevonmorgen.org/#/?center=50.616,8.262&zoom=11.00&search=%23hessenwillsmessen%20test&fixedTags=hessenwillsmessen&orgTag=hessenwillsmessen&dropdowns=hessenwillsmessen
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/220d2990-dd79-4d33-856a-d9a9b19fcfb7)

Obviously, you can not open the Test entry, as it is not visible, so no empty white page!

### Technical Background
- The correct request to fetch all entries in a bbox with orgTag would be: https://api.ofdb.io/v0/search?text=#hessenwillsmessen test&categories=2cd00bebec0c48ba9db761da48678134,c2dc278a2d6a4b9b8a50cb606fc017ed,77b3c33a92554bcf8e8c2c86cedd6f6f&bbox=50.48634732684517,7.822952270507813,50.745580217132755,8.701858520507814&limit=250&org_tag=hessenwillsmessen

- But the new front-end does not add the orgTag to the api Call: https://api.ofdb.io/v0/search?bbox=50.23572332598048,7.0853700020742325,50.9895922827563,9.641181067676344&text=test #hessenwillsmessen&categories=2cd00bebec0c48ba9db761da48678134,77b3c33a92554bcf8e8c2c86cedd6f6f

**Additional context**
This function on the new frontend is highly relvant for HLNUG. They use the clearance-Center to moderate their map, which is embedded on a govermental page. So no unapproved changes on the map should every be visible on a official public website.

**Comment by navid-kalaei** [comment]
fixed and deployed on the dev domain. please test. @wellemut

**Comment by wellemut** [comment]
@navid-kalaei thank you.
But on 
https://dev.kartevonmorgen.org/m/hessenwillsmessen?c=50.5517%2C9.6752&z=16.00&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=gray

The problem still exists.
This "Test" should not be visible in the result list
![Screenshot_20240326-204435~2.png](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/e02219b0-f5d7-471e-88d5-86ef8834241b)


The detailed view is correctly filtering for an approved version of the entry
![Screenshot_20240326-204439~3.png](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/635de49d-ecb8-41fe-9e0f-a908b632c40c)

**Comment by navid-kalaei** [comment]
@wellemut I'm confused, which format is correct: `orgTag` or `org_tag`? I implemented the `org_tag` should i change it/

**Comment by wellemut** [comment]
Perfect @navid-kalaei 
It is working now
https://dev.kartevonmorgen.org/m/hessenwillsmessen?c=50.5493%2C9.6724&z=16.00&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=gray

Please create the pull request for @alex0107

**Comment by navid-kalaei** [comment]
@wellemut @alex0107 created a new release of v1.2.1 https://github.com/kartevonmorgen/kartevonmorgen.ts/releases/tag/1.2.1
